---
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("cowplot")
library("devtools")
library("ggplot2")
library("ggpubr")
library("grid")
library("gridExtra")
library("lattice")
library("marelac")
library("scales")
library("zoo")
library("ggpubr")
```

#Site 1
####Longitude:  -83.11
####Latitude:    29.26

```{r r_site8, include= FALSE}
##### Site 1 Analysis with Diver sensor
setwd("C:/Users/melimore86/Desktop/Deployment/Lone Cabbage WQ Data/LC_WQ1/CSV")
LC_WQ1 <- read.csv("LC_WQ1_All_Days_R.csv", header= T)

#Naming columns, using the Diver sensors, collects date, pressure, temp, conductivity
colnames(LC_WQ1) <- c("DateTime_Serial", "Pressure", "Temperature", "Conductivity")
head(LC_WQ1)

#Changing the format of the dates to be able to plot against time
LC_WQ1$newDate <- as.POSIXct(as.Date(LC_WQ1$DateTime_Serial,origin= "1899-12-30"))

#Calculating salinity, using package `marelac` for this conversion 
standard=42.914
LC_WQ1$Salinity <- convert_RtoS(LC_WQ1$Conductivity/standard, 
                                t= LC_WQ1$Temperature, p= 0)

```
```{r r_RD, include=FALSE}
#This is the river discharge data from the package `waterData`

library("waterData")
library("hydroTSM")

#station to analyze
station = '02323500'   

#get site name to use in plot titles and such
stinfo  = siteInfo(station)

#read entire time series
dis   = importDVs(staid=station,code='00060',stat='00003', sdate= "1950-01-01") 
#ok looks like temp code is wrong for this station, maybe rainfall is available?

#get some date components
dis$year    = as.numeric(strftime(dis$dates,format="%Y"))
dis$month   = as.numeric(strftime(dis$dates,format="%m")) 

#make dataset from epochs, 
disE  = dis[dis$dates>='1950-01-01' & dis$dates<='2017-10-01',]  

#get monthly sum, mean, sd, and var
#discharge
disE.mo  = aggregate(val~month+year,data=disE,FUN = function(x) c(mean(x,na.rm=T),sd(x,na.rm=T),var(x,na.rm=T),sum(x)))
disE.mo  = do.call('data.frame',disE.mo)
names(disE.mo)[3:6] = c('avg','sd','var','sumflow') 
disE.mo$yrmo = disE.mo$year+(disE.mo$month-0.5)/12       


#get yearly mean, sd, and var
#discharge
disE.yr  = aggregate(val~year,data=disE,FUN = function(x) c(mean(x,na.rm=T),sd(x,na.rm=T),var(x,na.rm=T)))
disE.yr  = do.call('data.frame',disE.yr)
names(disE.yr)[2:4] = c('avg','sd','var')                      


#make some time series objects
disE.zoo    = zoo(disE$val,disE$dates)  

disE.mo.ts  = ts(disE.mo$avg,start=c(1950,1),end=c(2017,10),frequency=12)
disE.mo.sum.ts  = ts(disE.mo$sumflow,start=c(1950,1),end=c(2017,10),frequency=12)
disE.yr.ts  = ts(disE.yr$avg,start=1950,end=2017,frequency=1)

```

```{r RD_newdate, include= FALSE}
#### River Discharge, this data was gathered from the River Discharge R file, and retrieved that way, the information is in the Rhistory for this analysis
head(dis)

#Naming columns, using the Diver sensors, collects date, pressure, temp, conductivity
colnames(dis) <- c("StaID", "Values", "Date", "QualCode", "Year", "Month")
head(dis)

#Changing the format of the dates to be able to plot against time
dis$newDate <- as.POSIXct(as.Date(dis$Date,origin= "1899-12-30"))

```
```{r discretecode, include= FALSE}
setwd("C:/Users/melimore86/Desktop")
labresults <- read.csv("cedarkeylabresults.csv", header= T)

#Creating new column names
colnames(labresults) <- c("County", "Name", "Date", "Month", "Day","Year","Station", "Phosphorus", "Nitrogen", "Chlorophyll", "Secchi", "Secchi 2", "Color", "SpecificConductancemicro", "SpecificConductancemilli")

labresults$newDate <- as.POSIXct(as.Date(labresults$Date, origin= "1899-12-30"))

labresults$newDate <- as.POSIXct(as.Date(labresults$Date, "%m/%d/%Y"))

#create new column for the micro and milli siemens in Specific Conductance
#1 millisiemens [mS] = 1000 microsiemens [??S, uS]

labresults$allconduct<-NA

labresults$allconduct<-paste(labresults$SpecificConductancemilli,labresults$SpecificConductancemicro)

labresults$allconduct<-as.numeric(gsub('NA','',labresults$allconduct))


site1<-subset(labresults,Station=="1")
site2<-subset(labresults,Station=="2")
site3<-subset(labresults,Station=="3")
site4<-subset(labresults,Station=="4")
site5<-subset(labresults,Station=="5")
site6<-subset(labresults,Station=="6")

```





```{r r_var1, include= FALSE}
var1 <-
  ggplot(data= LC_WQ1, aes(x= newDate)) +
  #ggtitle("Salinity,Temperature, and River Discharge") +
  labs(x= "Date", y= "Temp(C) & Salinity (ppt)") +
  geom_ribbon(data= dis, aes(x= newDate, y=Values/500, ymin=0, ymax=Values/500, fill= "blue"), fill= "cornflowerblue", alpha=0.5) +
  geom_point(aes(y= Temperature, colour= "Temperature"), color= "red", size= .9) +
  geom_point(aes(y= Salinity, colour= "Salinity"), color= "#000000") +
  scale_y_continuous(sec.axis = sec_axis(~.*500, name = "River Discharge"), limits=c(0,40)) +
   scale_x_datetime(
    breaks = date_breaks("2 weeks") ,
    labels = date_format("%m/%d/%y"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-01-30"))) +
  theme(panel.border = element_rect(color = "black", size = 0.5, fill = NA, linetype="solid"),
        axis.text=element_text(size=12),
        axis.title=element_text(size=15,face="bold"),
        plot.title =element_text(size=20, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1,size=12),
        aspect.ratio = 0.70)

```

```{r r_legend, include=FALSE}
legend <- 
  ggplot() +
  geom_point(data= LC_WQ1, aes(y= Salinity, x= newDate, fill= "Salinity"), color= "#999999") +
  geom_point(data= LC_WQ1, aes(x= newDate, y= Temperature, fill= "Temperature"), color= "red") +
  geom_point(data= dis, aes(x= newDate, y=Values/1000, fill= "River Discharge"), color="cornflowerblue", size=1, show.legend = TRUE, pch=15, alpha=0.4) +
  guides(fill= guide_legend(show= TRUE, title="", override.aes= list(colour= c("cornflowerblue", "#000000", "red"), size=10))) +
  scale_y_continuous(sec.axis = sec_axis(~.*600, name = "River Discharge"), limits=c(0,40)) +
  theme(legend.position = "bottom", legend.text=element_text(size=15))

#creating a legend, to "grob" later in the ggdraw
legend_b <- get_legend(legend + theme(legend.position="bottom"))

```

```{r r_ggdraw, warning=FALSE, echo= FALSE}
ggdraw() +
  draw_plot(var1, x=0, y=0, width=.8, height=.8 ) +
  draw_grob(legend_b, 0.9/3, 0.74, 2/7, 0.4, scale=0) 

```

