---
title: "test_ani"
author: "Melissa Moreno"
date: "March 14, 2018"
output: html_document
---



```{r}
library(cowplot)
library(devtools)
library(ggplot2)
library(ggpubr)
library(grid)
library(gridExtra)
library(plotly)
library(lattice)
library(lubridate)
library(marelac)
library(scales)
library(marelac)
library(plotly)
library(shiny)
library(shinythemes)
```


```{r , include=FALSE}

setwd("C:/Users/melimore86/Desktop/Deployment/Lone Cabbage WQ Data/LC_WQ1/CSV")
LC_WQ1 <- read.csv("LC_WQ1_All_Days_R.csv", header= T)

colnames(LC_WQ1) <- c("DateTime_Serial", "Pressure", "Temperature", "Conductivity")

LC_WQ1$newDate <- as.POSIXct(as.Date(LC_WQ1$DateTime_Serial,origin= "1899-12-30"))

standard= 42.914

LC_WQ1$Salinity <- convert_RtoS(LC_WQ1$Conductivity/standard, 
                                t= LC_WQ1$Temperature, p= 0)
  
```
```{r , include=FALSE}
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

d <- LC_WQ1 %>%
  accumulate_by(~newDate)

```


```{r , include=FALSE}

  p <- d %>%
    plot_ly(
      x = ~newDate, 
      y = ~Salinity,
      frame = ~newDate, 
      type = 'scatter',
      mode = 'lines', 
      line = list(simplyfy = F)
    ) %>% 
    layout(
      xaxis = list(
        title = "Date",
        zeroline = F
      ),
      yaxis = list(
        title = "Salinity",
        zeroline = F
      )
    ) %>% 
    animation_opts(
      frame = 100, 
      transition = 0, 
      redraw = FALSE
    ) %>%
    animation_slider(
      hide = T
    ) %>%
    animation_button(
      x = 1, xanchor = "right", y = 0, yanchor = "bottom"
    )
  
```




```{r finalplot, echo=FALSE, fig.width=8,fig.height=6, warning= FALSE,  message=FALSE}
  
    p
 
```

