---
title: "testing_ani"
author: "Melissa Moreno"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include= FALSE}
library(plotly)
library(quantmod)
```



```{r pressure, echo=FALSE}


getSymbols("YAHOO",src='yahoo')

df <- data.frame(Date=index(YAHOO),coredata(YAHOO))

high_annotations <- list(
  x=df$Date[df$YAHOO.High == max(df$YHOO.High)], 
  y=max(df$YAHOO.High),
  xref='x', yref='y',
  text=paste0('High: $',max(df$YAHOO.High)),
  ax=0, ay=-40
)

low_annotations <- list(
  x=df$Date[df$YAHOO.Low == min(df$YAHOO.Low)], 
  y=min(df$YAHOO.Low),
  xref='x', yref='y',
  text=paste0('Low: $',min(df$YAHOO.Low)),
  ax=0, ay=40
)

# updatemenus component
updatemenus <- list(
  list(
    active = -1,
    type= 'buttons',
    buttons = list(
      list(
        label = "High",
        method = "update",
        args = list(list(visible = c(FALSE, TRUE)),
                    list(title = "Yahoo High",
                         annotations = list(c(), high_annotations)))),
      list(
        label = "Low",
        method = "update",
        args = list(list(visible = c(TRUE, FALSE)),
                    list(title = "Yahoo Low",
                         annotations = list(low_annotations, c() )))),
      list(
        label = "Both",
        method = "update",
        args = list(list(visible = c(TRUE, TRUE)),
                    list(title = "Yahoo",
                         annotations = list(low_annotations, high_annotations)))),
      list(
        label = "Reset",
        method = "update",
        args = list(list(visible = c(TRUE, TRUE)),
                    list(title = "Yahoo",
                         annotations = list(c(), c())))))
  )
)

p <- df %>%
  plot_ly(type = 'scatter', mode = 'lines') %>%
  add_lines(x=~Date, y=~YAHOO.High, name="High",
            line=list(color="#33CFA5")) %>%
  add_lines(x=~Date, y=~YAHOO.Low, name="Low",
            line=list(color="#F06A6A")) %>%
  layout(title = "Yahoo", showlegend=FALSE,
         xaxis=list(title="Date"),
         yaxis=list(title="Price ($)"),
         updatemenus=updatemenus)
```


```{r finalplot, echo=FALSE, fig.width=8,fig.height=6, warning= FALSE,  message=FALSE}
  
    p
 
```